# Uncomment this line to define a global platform for your project

platform :ios, "8.0"

target 'Demo' do

    pod 'MJRefresh'
    pod 'SDWebImage', '3.7.5'
    
    pod 'LuaViewSDK', :git => 'https://github.com/alibaba/LuaViewSDK.git',  :branch=>'develop'
    pod 'luaviewEx', :path => '../luaviewEx'
end

