# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

platform :ios, "8.0"

target 'LuaViewSDK' do
    pod 'liblua', '5.1.4.3'
end

target 'Dummy' do

end

target 'LuaViewLib' do

end

