# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

platform :ios, "8.0"

target 'LuaViewSDK' do
    pod 'liblua', :git => 'git@gitlab.alibaba-inc.com:luaview/LuaViewSDK.git', :branch => 'develop'
    #pod 'liblua', :git => 'https://github.com/alibaba/LuaViewSDK.git', :branch => 'develop'
end

target 'Dummy' do

end

target 'LuaViewLib' do

end

