# Uncomment this line to define a global platform for your project

platform :ios, "6.0"

def demo_pods
    pod 'JUFLXLayoutKit',   :git => 'git@gitlab.alibaba-inc.com:juhuasuanwireless/JUFLXLayoutKit.git'
    pod 'MJRefresh'
    pod 'SDWebImage',   :git => 'https://github.com/rs/SDWebImage.git'
end

def sdk_pods
    pod 'JUFLXLayoutKit',   :git => 'git@gitlab.alibaba-inc.com:juhuasuanwireless/JUFLXLayoutKit.git'
end

target 'Demo' do
    platform :ios, '6.0'
    demo_pods
end

target 'LuaViewSDK' do
    platform :ios, '6.0'
    sdk_pods
end

