# Uncomment this line to define a global platform for your project

platform :ios, "7.0"

def demo_pods
    pod 'MJRefresh'
    pod 'SDWebImage',   :git => 'https://github.com/rs/SDWebImage.git'
end

def sdk_pods
end

target 'Demo' do
    platform :ios, '7.0'
    demo_pods
end

target 'LuaViewSDK' do
    platform :ios, '7.0'
    sdk_pods
end

